const characterInfo = {
    albedo: {
        name: "Albedo",
        weapon: "Sword",
        element: "Geo",
        region: "Mondstadt",
        version: "1.2",
        talents: "Ballad",
        boss: "Tusk of Monoceros Caeli",
        stat: "Geo DMG Bonus",
        affiliation: "Knights of Favonius"
    },
    alhaitham: {
        name: "Alhaitham",
        weapon: "Sword",
        element: "Dendro",
        region: "Sumeru",
        version: "3.4",
        talents: "Ingenuity",
        boss: "Mirror of Mushin",
        stat: "Dendro DMG Bonus",
        affiliation: "Sumeru Akademiya"
    },
    ayaka: {
        name: "Ayaka",
        weapon: "Sword",
        element: "Cryo",
        region: "Inazuma",
        version: "2.0",
        talents: "Elegance",
        boss: "Bloodjade Branch",
        stat: "CRIT DMG",
        affiliation: "Yashiro Commission"
    },
    baizhu: {
        name: "Baizhu",
        weapon: "Catalyst",
        element: "Dendro",
        region: "Liyue",
        version: "3.6",
        talents: "Gold",
        boss: "World­span Fern",
        stat: "HP",
        affiliation: "Bubu Pharmacy"
    },
    tartaglia: {
        name: "Tartaglia",
        weapon: "Bow",
        element: "Hydro",
        region: "Snezhnaya",
        version: "1.1",
        talents: "Freedom",
        boss: "Shard of a Foul Legacy",
        stat: "Hydro DMG Bonus",
        affiliation: "Fatui"
    },
    cyno: {
        name: "Cyno",
        weapon: "Polearm",
        element: "Electro",
        region: "Sumeru",
        version: "3.1",
        talents: "Admonition",
        boss: "Mudra of the Malefic General",
        stat: "CRIT DMG",
        affiliation: "Temple of Silence"
    },
    dehya: {
        name: "Dehya",
        weapon: "Claymore",
        element: "Pyro",
        region: "Sumeru",
        version: "3.5",
        talents: "Praxis",
        boss: "Puppet Strings",
        stat: "HP",
        affiliation: "The Eremites"
    },
    diluc: {
        name: "Diluc",
        weapon: "Claymore",
        element: "Pyro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Resistance",
        boss: "Dvalin's Plume",
        stat: "CRIT Rate",
        affiliation: "Dawn Winery"
    },
    eula: {
        name: "Eula",
        weapon: "Claymore",
        element: "Cryo",
        region: "Mondstadt",
        version: "1.5",
        talents: "Resistance",
        boss: "Dragon Lord's Crown",
        stat: "CRIT DMG",
        affiliation: "Knights of Favonius"
    },
    furina: {
        name: "Furina",
        weapon: "Sword",
        element: "Hydro",
        region: "Fontaine",
        version: "4.2",
        talents: "Justice",
        boss: "Lightless Mass",
        stat: "CRIT Rate",
        affiliation: "Court of Fontaine"
    },
    ganyu: {
        name: "Ganyu",
        weapon: "Bow",
        element: "Cryo",
        region: "Liyue",
        version: "1.2",
        talents: "Diligence",
        boss: "Shadow of the Warrior",
        stat: "CRIT DMG",
        affiliation: "Yuehai Pavilion"
    },
    hu_tao: {
        name: "Hu Tao",
        weapon: "Polearm",
        element: "Pyro",
        region: "Liyue",
        version: "1.3",
        talents: "Diligence",
        boss: "Shard of a Foul Legacy",
        stat: "CRIT DMG",
        affiliation: "Wangsheng Funeral Parlor"
    },
    itto: {
        name: "Itto",
        weapon: "Claymore",
        element: "Geo",
        region: "Inazuma",
        version: "2.3",
        talents: "Elegance",
        boss: "Ashen Heart",
        stat: "CRIT Rate",
        affiliation: "Arataki Gang"
    },
    jean: {
        name: "Jean",
        weapon: "Sword",
        element: "Anemo",
        region: "Mondstadt",
        version: "1.0",
        talents: "Resistance",
        boss: "Dvalin's Plume",
        stat: "Healing Bonus",
        affiliation: "Knights of Favonius"
    },
    kazuha: {
        name: "Kaedehara Kazuha",
        weapon: "Sword",
        element: "Anemo",
        region: "Inazuma",
        version: "1.6",
        talents: "Diligence",
        boss: "Glided Scale",
        stat: "Elemental Mastery",
        affiliation: "The Crux"
    },
    keqing: {
        name: "Keqing",
        weapon: "Sword",
        element: "Electro",
        region: "Liyue",
        version: "1.0",
        talents: "Prosperity",
        boss: "Ring of Boreas",
        stat: "CRIT DMG",
        affiliation: "Liyue Qixing"
    },
    klee: {
        name: "Klee",
        weapon: "Catalyst",
        element: "Pyro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Freedom",
        boss: "Ring of Boreas",
        stat: "Pyro DMG Bonus",
        affiliation: "Knights of Favonius"
    },
    kokomi: {
        name: "Sangonomiya Kokomi",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Inazuma",
        version: "2.1",
        talents: "Transience",
        boss: "Hellfire Butterfly",
        stat: "Hydro DMG Bonus",
        affiliation: "Watatsumi Island"
    },
    lyney: {
        name: "Lyney",
        weapon: "Bow",
        element: "Pyro",
        region: "Fontaine",
        version: "4.0",
        talents: "Equity",
        boss: "Primor­dial Green­bloom",
        stat: "CRIT Rate",
        affiliation: "Hotel Bouffes d'ete"
    },
    mona: {
        name: "Mona",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Resistance",
        boss: "Ring of Boreas",
        stat: "Energy Recharge",
        affiliation: "Mondstadt"
    },
    nahida: {
        name: "Nahida",
        weapon: "Catalyst",
        element: "Dendro",
        region: "Sumeru",
        version: "3.2",
        talents: "Ingenuity",
        boss: "Puppet Strings",
        stat: "Elemental Mastery",
        affiliation: "Sumeru City"
    },
    navia: {
        name: "Navia",
        weapon: "Claymore",
        element: "Geo",
        region: "Fontaine",
        version: "4.3",
        talents: "Equity",
        boss: "Lightless Silk String",
        stat: "CRIT DMG",
        affiliation: "Spina di Rosula"
    },
    neuvillette: {
        name: "Navia",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Fontaine",
        version: "4.1",
        talents: "Equity",
        boss: "Ever­amber",
        stat: "CRIT DMG",
        affiliation: "Court of Fontaine"
    },
    nilou: {
        name: "Nilou",
        weapon: "Sword",
        element: "Hydro",
        region: "Sumeru",
        version: "3.1",
        talents: "Praxis",
        boss: "Tears of the Calamitous God",
        stat: "HP",
        affiliation: "Zubayr Theater"
    },
    qiqi: {
        name: "Qiqi",
        weapon: "Sword",
        element: "Cryo",
        region: "Liyue",
        version: "1.0",
        talents: "Prosperity",
        boss: "Tail of Boreas",
        stat: "Healing Bonus",
        affiliation: "Bubu Pharmacy"
    },
    raiden_shogun: {
        name: "Raiden Shogun",
        weapon: "Polearm",
        element: "Electro",
        region: "Inazuma",
        version: "1.0",
        talents: "Prosperity",
        boss: "Tail of Boreas",
        stat: "Healing Bonus",
        affiliation: "Bubu Pharmacy"
    },
    shenhe: {
        name: "Shenhe",
        weapon: "Polearm",
        element: "Cryo",
        region: "Liyue",
        version: "2.4",
        talents: "Prosperity",
        boss: "Hellfire Butterfly",
        stat: "ATK",
        affiliation: "Cloud Retainer's Abode"
    },
    tighnari: {
        name: "Tighnari",
        weapon: "Bow",
        element: "Dendro",
        region: "Sumeru",
        version: "3.0",
        talents: "Admonition",
        boss: "The Meaning of Aeons",
        stat: "Dendro DMG Bonus",
        affiliation: "Gandharva Ville"
    },
    venti: {
        name: "Venti",
        weapon: "Bow",
        element: "Anemo",
        region: "Liyue",
        version: "1.0",
        talents: "Ballad",
        boss: "Tail of Boreas",
        stat: "Energy Recharge",
        affiliation: "Mondstadt"
    },
    wanderer: {
        name: "Wanderer",
        weapon: "Catalyst",
        element: "Anemo",
        region: "Sumeru",
        version: "3.3",
        talents: "Praxis",
        boss: "Daka's Bell",
        stat: "CRIT Rate",
        affiliation: "None"
    },
    wriothesley: {
        name: "Wriothesley",
        weapon: "Catalyst",
        element: "Cryo",
        region: "Fontaine",
        version: "4.1",
        talents: "Order",
        boss: "Primor­dial Green­bloom",
        stat: "CRIT DMG",
        affiliation: "Fortress of Meropide"
    },
    xianyun: {
        name: "Xianyun",
        weapon: "Catalyst",
        element: "Anemo",
        region: "Liyue",
        version: "4.4",
        talents: "Gold",
        boss: "Lightless Eye of the Maelstrom",
        stat: "ATK",
        affiliation: "Mt. Aocang"
    },
    xiao: {
        name: "Xiao",
        weapon: "Polearm",
        element: "Anemo",
        region: "Liyue",
        version: "1.3",
        talents: "Prosperity",
        boss: "Shadow of the Warrior",
        stat: "CRIT Rate",
        affiliation: "Liyue Adeptus"
    },
    yae_miko: {
        name: "Yae Miko",
        weapon: "Catalyst",
        element: "Electro",
        region: "Inazuma",
        version: "2.5",
        talents: "Light",
        boss: "The Meaning of Aeons",
        stat: "CRIT Rate",
        affiliation: "Grand Narukami Shrine"
    },
    yelan: {
        name: "Yelan",
        weapon: "Bow",
        element: "Hydro",
        region: "Liyue",
        version: "2.7",
        talents: "Prosperity",
        boss: "Gilded Scale",
        stat: "CRIT Rate",
        affiliation: "Yanshang Teahouse"
    },
    yoimiya: {
        name: "Yoimiya",
        weapon: "Bow",
        element: "Pyro",
        region: "Inazuma",
        version: "2.0",
        talents: "Transience",
        boss: "Dragon Lord's Crown",
        stat: "CRIT Rate",
        affiliation: "Naganohara Fireworks"
    },
    zhongli: {
        name: "Zhongli",
        weapon: "Polearm",
        element: "Geo",
        region: "Liyue",
        version: "1.1",
        talents: "Gold",
        boss: "Tusk of Monoceros Caeli",
        stat: "Geo DMG Bonus",
        affiliation: "Liyue Harbor"
    },
    amber: {
        name: "Amber",
        weapon: "Bow",
        element: "Pyro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Freedom",
        boss: "Dvalin's Sigh",
        stat: "ATK",
        affiliation: "Knights of Favonius"
    },
    barbara: {
        name: "Barbara",
        weapon: "Catalyst",
        element: "Hydro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Freedom",
        boss: "Ring of Boreas",
        stat: "HP",
        affiliation: "Knights of Favonius"
    },
    beidou: {
        name: "Beidou",
        weapon: "Claymore",
        element: "Electro",
        region: "Liyue",
        version: "1.0",
        talents: "Gold",
        boss: "Dvalin's Sigh",
        stat: "Electro DMG Bonus",
        affiliation: "Knights of Favonius"
    },
    bennett: {
        name: "Bennett",
        weapon: "Sword",
        element: "Pyro",
        region: "Mondstadt",
        version: "1.0",
        talents: "Resistance",
        boss: "Dvalin's Plume",
        stat: "Energy Recharge",
        affiliation: "Adventurers' Guild"
    },
    candace: {
        name: "Candace",
        weapon: "Polearm",
        element: "Hydro",
        region: "Sumeru",
        version: "3.1",
        talents: "Admonition",
        boss: "Tears of the Calamitous God",
        stat: "HP",
        affiliation: "Aaru Village"
    },
    charlotte: {
        name: "Charlotte",
        weapon: "Catalyst",
        element: "Cryo",
        region: "Fontaine",
        version: "4.2",
        talents: "Justice",
        boss: "Lightless Silk String",
        stat: "ATK",
        affiliation: "The Steambird"
    },
    chevreuse: {
        name: "Chevreuse",
        weapon: "Polearm",
        element: "Pyro",
        region: "Fontaine",
        version: "4.3",
        talents: "Order",
        boss: "Lightless Eye of the Maelstrom",
        stat: "HP",
        affiliation: "Special Security and Surveillance Patrol"
    },
    chevreuse: {
        name: "Chevreuse",
        weapon: "Polearm",
        element: "Pyro",
        region: "Fontaine",
        version: "4.3",
        talents: "Order",
        boss: "Lightless Eye of the Maelstrom",
        stat: "HP",
        affiliation: "Special Security and Surveillance Patrol"
    },
    chongyun: {
        name: "Chongyun",
        weapon: "Claymore",
        element: "Cryo",
        region: "Liyue",
        version: "1.0",
        talents: "Diligence",
        boss: "Dvalin's Sigh",
        stat: "ATK",
        affiliation: "Tianheng Thaumaturges"
    },
    collei: {
        name: "Collei",
        weapon: "Bow",
        element: "Dendro",
        region: "Sumeru",
        version: "3.0",
        talents: "Praxis",
        boss: "Tears of the Calamitous God",
        stat: "ATK",
        affiliation: "Gandharva Ville"
    },
    diona: {
        name: "Diona",
        weapon: "Bow",
        element: "Cryo",
        region: "Monstadt",
        version: "1.1",
        talents: "Freedom",
        boss: "Shard of a Foul Legacy",
        stat: "Cryo DMG Bonus",
        affiliation: "The Cat's Tail"
    },
    dori: {
        name: "Dori",
        weapon: "Claymore",
        element: "Electro",
        region: "Sumeru",
        version: "3.0",
        talents: "Ingenuity",
        boss: "Bloodjade Branch",
        stat: "HP",
        affiliation: "The Palace of Alcazarzaray"
    },
};

// export default characterInfo;
